image: # see: https://quay.io/repository/kiali/kiali-operator?tab=tags
  repo: arti.paas.telekom.hu/quay-remote/kiali/kiali-operator # quay.io/kiali/kiali-operator

# Defines where the operator will look for Kial CR resources. "" means "all namespaces".
watchNamespace: "istio-system"

# For what a Kiali CR spec can look like, see:
# https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml
allowAdHocKialiImage: true
cr:
  create: false
  name: kiali
  # If you elect to create a Kiali CR (--set cr.create=true)
  # and the operator is watching all namespaces (--set watchNamespace="")
  # then this is the namespace where the CR will be created (the default will be the operator namespace).
  namespace: "istio-system"

  spec:
    deployment:
      accessible_namespaces:
      - '**'

